version: "3"

services:
    redis-db:
        image: redis:7
        ports:
            - 6379:6379
        volumes:
            - ./data:/data
        user: "1000:1000"
        command: ["--save", "1", "1"]
    flask-app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        depends_on:
            - redis-db
        image: dylmcintyre/final_api:1.0
        environment:
            - REDIS_IP=redis-db
        ports:
            - 5000:5000
        command: ["python3", "app.py"]
   worker:
      build:
          context: ./
          dockerfile: ./Dockerfile
      depends_on:
            - redis-db
      image: dylmcintyre/final_api:1.0
      environment:
            - REDIS_IP=redis-db
      command: ["python3", "worker.py"]
